# Generated by Django 3.1.6 on 2021-02-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20210220_2012'),
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='dry_weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='harvest',
            unique_together={('farm', 'year')},
        ),
    ]
