# Generated by Django 3.1.6 on 2021-02-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_farmer_farmerlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='id_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
