# Generated by Django 3.1.6 on 2021-02-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='deed_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
